siteUid: null
sortOrder: 5
template: /freeform-demo/templates/form
uriParts:
  - freeform-demo/templates/
  -
    - '*'
    - '[^\/]+'
  - /
  -
    - '*'
    - '[^\/]+'
  - /edit/
  -
    - '*'
    - '[^\/]+'
uriPattern: 'freeform-demo/templates/<any:[^\/]+>/<any2:[^\/]+>/edit/<any3:[^\/]+>'
