siteUid: null
sortOrder: 8
template: /freeform-demo/submissions/view
uriParts:
  - freeform-demo/submissions/
  -
    - '*'
    - '[^\/]+'
  - /
  -
    - '*'
    - '[^\/]+'
uriPattern: 'freeform-demo/submissions/<any:[^\/]+>/<any2:[^\/]+>'
