siteUid: null
sortOrder: 7
template: /freeform-demo/submissions
uriParts:
  - freeform-demo/submissions/
  -
    - '*'
    - '[^\/]+'
  - /spam/
uriPattern: 'freeform-demo/submissions/<any:[^\/]+>/spam/'
