fieldLayouts:
  89492908-8597-43b0-94ad-f08fca684b4f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-26T10:36:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Label
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ed91e688-b40d-4040-95f5-8fa6c71e1b32
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e71c48e2-d45d-4702-86a5-de743b39b483
        userCondition: null
handle: productTag
name: 'Product Tag'
