color: null
fieldLayouts:
  59097df0-d63f-43ec-aa8d-a17509d8cddf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T09:02:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62534679-40fc-45ab-9544-cbced2386fe8 # Media
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e631ee3-ad0c-445f-8cf3-b96d1100e486
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f4e88ffc-3554-458b-926b-81774b9422a5
        userCondition: null
handle: carouselSlide
hasTitleField: false
icon: photo-film
name: 'Carousel Slide'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
