color: null
fieldLayouts:
  5332d3ff-8966-4ff4-8317-526d67bf924d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-20T15:51:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74347a8e-2aa2-47d7-a77d-bdd9012c07fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-20T15:55:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0b7df609-3386-44d6-8dec-9236996e999a # Link List
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67d0b562-a644-4f8f-9703-8d0165c2e534
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d29532a6-05eb-4df0-8134-cb33775c55ed
        userCondition: null
handle: megamenuList
hasTitleField: true
icon: null
name: 'Megamenu List'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
