color: null
fieldLayouts:
  8be5db49-a817-457e-9443-6a798792cc0a:
    cardView:
      - 'layoutElement:a026ab43-e6b0-4a07-86c3-713cc9ce2e7c'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-02T09:33:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Label
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 948b8353-e96d-4586-a3c8-bf0a614850a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-02T09:36:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 10d13899-8189-48c3-9250-da714101745f # Nav Link
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a026ab43-e6b0-4a07-86c3-713cc9ce2e7c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-02T10:12:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7237097a-258e-4778-abe5-339d6c644bba # Navigation
            handle: submenu
            includeInCards: false
            instructions: null
            label: Submenu
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dc14c7d-a75e-4c8e-8787-29b2d03dfcdb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d2f5708-49cb-4f56-b5e1-6108149facb7
        userCondition: null
handle: navItem
hasTitleField: true
icon: null
name: 'Nav Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
