color: null
fieldLayouts:
  d5c21c6e-c878-43d9-adc2-ef741f25a3e4:
    cardView:
      - drafts
      - type
      - link
      - dateUpdated
      - revisionNotes
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-30T15:11:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92f9451a-10f0-48f9-a26c-94fa80c9c397
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T15:13:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: edfdf431-f3cd-4069-b00d-d7b1fbbe9bb7 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b87072e7-2789-48a6-b096-0301cae4f81a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2109da0f-6a49-4be5-8596-8e1b634a457e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-02T10:58:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8501eb95-03e9-42c4-8cdf-17a231b14111 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85a072ac-5afd-4bb8-b6d7-5fa0393e1dea
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 94bd6f30-c578-4c64-8f4d-f4ef260e99a2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-03T11:47:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6ea8cc63-a255-48ca-9ae6-d893d262a7df # True/false
            handle: darkHeader
            includeInCards: false
            instructions: 'Changes the header to show the dark version (Darker logo and menu item text etc)'
            label: 'Dark Header?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c5775cb-b7e2-46d3-aa84-b5a22ae2e0f7
            userCondition: null
            warning: null
            width: 100
        name: 'Page Options'
        uid: 97681695-9ae4-4a28-87d7-fcaebdde9f41
        userCondition: null
handle: page
hasTitleField: true
icon: page
name: Pages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
