color: null
fieldLayouts:
  adc2451c-6b98-437b-80b5-f46fe18af851:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-30T13:21:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a62ebacf-1267-4dee-a63f-c2d6baad1047
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T14:03:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: edfdf431-f3cd-4069-b00d-d7b1fbbe9bb7 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a813057c-ab89-4f66-866d-682597202ad7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 126b92be-d8d2-40a3-ba2e-4b3d95af5925
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-02T10:58:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8501eb95-03e9-42c4-8cdf-17a231b14111 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef667d57-1b74-4139-8f86-e42e0c2ce4ba
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9dfbdd0c-ec0b-44fa-9c62-0fef808abf86
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-30T14:03:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 14e7adcd-0bb5-424c-b7c5-0181f85b89bd # Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23e495e1-47a3-499e-948a-2dc1cebe652e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T14:03:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 136014f7-4b03-4882-a502-767d68d5d198 # Subtext
            handle: summary
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec1259e9-56a7-4b57-b445-8ad3a898d0b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-05T11:07:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ec030511-3ca4-4860-bf00-5396c90d7afb # Image
            handle: thumbnailImage
            includeInCards: false
            instructions: null
            label: 'Thumbnail Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2d4b725-e31d-48ff-8365-5db6f37fbd91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-05T11:18:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 02066fa3-3504-472a-b9df-f795a8992d73 # Image/Video
            handle: hoverImage
            includeInCards: false
            instructions: null
            label: 'Hover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9a54f2d-483d-4958-a936-65553b5511e2
            userCondition: null
            warning: null
            width: 100
        name: 'Post Options'
        uid: 32e0f20f-fa26-4bb8-8272-5f839f049e01
        userCondition: null
handle: post
hasTitleField: true
icon: file-circle-plus
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
