color: null
fieldLayouts:
  6855aa04-7aa5-49ae-ab98-012a5905cd0a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-02T15:19:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62534679-40fc-45ab-9544-cbced2386fe8 # Media
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6924c78-05b9-4f0f-871f-b3f556aa1810
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-02T15:15:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc804abb-728f-4355-9390-1d1ae3bb9a2d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T15:19:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 31515169-58e5-4fdf-b1f0-0060aba7da2f # Subtext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 622f27a0-d795-4aee-a364-1f97f5c565ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T15:19:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 312021f4-e37c-4cd4-a5cc-948fec2a9862 # Product Page Details
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68adf414-6317-499f-b59c-00c9464d4b71
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T15:21:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 25b44531-448b-4689-84e9-8af1f8ebda2a # Wanted Equipment Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bec1aed4-fec7-434d-a87c-d4864bd85c04
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e99f2fe-be4a-48b4-8172-f2b0ccd6ee21
        userCondition: null
handle: wantedEquipmentCard
hasTitleField: true
icon: null
name: 'Wanted Equipment Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
