altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  608d9f22-472f-48c9-903f-7e624d3a9d23:
    cardView:
      - dateUpdated
      - dateCreated
      - filename
      - link
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-30T11:58:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4024d6a4-a750-4f0a-b593-0d669b9dfb72
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 023972a0-b06a-420b-83b1-6c36b5637c8e
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: images
