columnSuffix: null
handle: content
instructions: null
name: Content
searchable: true
settings:
  createButtonLabel: 'Add block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 65e7af92-94af-4bcb-9a86-22f17bfc38d0 # Video/Image Hero
    -
      __assoc__:
        -
          - uid
          - 22395dd6-2252-4b6b-b5cd-3a0035f4a296 # Intro Text Block
    -
      __assoc__:
        -
          - uid
          - da8a7f7f-8fbc-4914-83ca-9c3babc6a78e # Services List Block
    -
      __assoc__:
        -
          - uid
          - fc0b742d-1087-408f-91d5-94e0443a43a4 # Full Width Media Carousel
    -
      __assoc__:
        -
          - uid
          - b9e48fb4-5c94-4f3b-b194-b8fa2bde12b7 # Two Column Text Block
    -
      __assoc__:
        -
          - uid
          - a17cffe2-4a21-4a03-9114-754a9a70f432 # Logo Carousel
    -
      __assoc__:
        -
          - uid
          - 0b581fc7-0baa-42ad-84a2-937679b1f7bd # Four Column Text Block
    -
      __assoc__:
        -
          - uid
          - 0268c6e2-41de-4328-9c29-5997c0303a3e # Projects Listing grid
    -
      __assoc__:
        -
          - uid
          - ec478c77-bac1-48cf-a257-9cee6fe9a5d0 # News Listing Carousel
    -
      __assoc__:
        -
          - uid
          - d957be7b-f06b-47f8-8d74-a33d6c18ac00 # CTA Banner
    -
      __assoc__:
        -
          - uid
          - b3601899-b39a-4f3e-b95d-a99ea789134e # Get Quote Hero
    -
      __assoc__:
        -
          - uid
          - 8e47b25b-5cc1-4741-b033-f13c25e594df # Services Tab Block
    -
      __assoc__:
        -
          - uid
          - b771e5be-a5e6-4ec7-a07a-95ba993074d2 # Accordion Block
    -
      __assoc__:
        -
          - uid
          - 4ae9d31c-cf60-4c3f-ad9e-a0ac9f1ab6c2 # Form Hero
    -
      __assoc__:
        -
          - uid
          - 4af4ea8b-c1db-4ead-a0c1-5bb6d2731bd0 # Simple Text Hero
    -
      __assoc__:
        -
          - uid
          - cb557252-9ee5-4cf2-a5cd-52172b72661b # Narrow Single Column Text
    -
      __assoc__:
        -
          - uid
          - 63b21fb4-099d-4449-83e0-c5eecda3b7e5 # Two Column Media Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
