columnSuffix: null
handle: equipmentPageType
instructions: null
name: 'Equipment Page Type'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Main Parent (Equipment List Page)'
        -
          - value
          - mainParent
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Category Listing Page'
        -
          - value
          - categoryListingPage
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Product Listing Page'
        -
          - value
          - productListingPage
        -
          - icon
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Product Individual Page'
        -
          - value
          - productIndividualPage
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
