columnSuffix: null
handle: singleLink
instructions: null
name: 'Single Link'
searchable: false
settings:
  advancedFields:
    - target
    - class
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
