dateModified: 1751378337
email:
  fromEmail: dev@in-testing.co.uk
  fromName: Sub
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@uploads'
meta:
  __names__:
    0b7df609-3386-44d6-8dec-9236996e999a: 'Link List' # Link List
    0de456be-e57c-491d-b5e9-2a48c94a73cf: 'Fifty Fifty Card' # Fifty Fifty Card
    1ed4c77a-2163-41cd-a3b4-dac5650b0ea3: 'Equipment List Pages' # Equipment List Pages
    3a4016c0-b8ce-4030-a761-17bbd4cb565f: 'Listing Card Tag' # Listing Card Tag
    8c5c2d88-d621-448b-81ae-1f21849e4f56: Sub # Sub
    27b88dbb-5275-488c-8cb3-86e8daa4b84f: 'Equipment Page Type' # Equipment Page Type
    37bcb295-e211-4822-b8ef-9119df20f58e: 'Page Content' # Page Content
    46e91064-492e-4832-8b32-9ea816047e2d: Heading # Heading
    75c37449-5a52-49a5-9e4a-f3533695f300: Navigation # Navigation
    114e0eaa-67db-473a-a450-04a4a53bba35: Footer # Footer
    208b59dc-efeb-404c-98f2-6ec660879ee1: 'Single Link' # Single Link
    674fb744-b160-444b-af35-72f3a327afbf: 'Two Column Card Block' # Two Column Card Block
    741d13d8-7c1b-4440-a507-1b6478eb6736: 'Fifty Fifty Repeater' # Fifty Fifty Repeater
    861d3103-01e5-446c-b19c-8357db15e40d: Header # Header
    09043f1e-ea69-4028-8ca3-5f75660d3d3d: Subtext # Subtext
    20033fea-bd0d-4a3e-ad47-9f84788a37db: 'CTA With Background' # CTA With Background
    69332d09-4481-4eaf-9f75-241fbd7f5211: 'Megamenu Content' # Megamenu Content
    312021f4-e37c-4cd4-a5cc-948fec2a9862: 'Product Page Details' # Product Page Details
    409531c9-59ff-4658-9ca0-41d34bc7bc30: Homepage # Homepage
    4494340c-3b4f-4bb8-a887-fa3b6f110dc1: Sub # Sub
    26919202-5503-4b47-913f-a7b707940ad8: Headings # Headings
    31515169-58e5-4fdf-b1f0-0060aba7da2f: Subtext # Subtext
    62534679-40fc-45ab-9544-cbced2386fe8: Media # Media
    a92e5168-e1b1-4553-88ea-8b38892b8c65: 'Megamenu List' # Megamenu List
    b375a142-d6d8-4f54-b238-08c6e1dc7e07: 'Detail Text' # Detail Text
    bcded55c-424c-4973-b666-df8c107909d2: 'Equipment Cards' # Equipment Cards
    c190d294-d2f4-4f8b-a3f9-bbc414f9e870: Simple # Simple
    ca7c778b-1c9d-4e2a-83a5-984c98a48619: 'Main Content' # Main Content
    cb061430-787b-48ea-8a9b-c7980d0134b9: 'Megamenu Item' # Megamenu Item
    cdb88818-0242-4279-92e9-21a22e0931cb: '50/50 Image Text Repeater' # 50/50 Image Text Repeater
    d4e7a80b-80bb-4ab2-a2f1-c58e7d49ed90: 'Product Listing Block' # Product Listing Block
    e1d477b7-f94e-41e1-94f9-0a657534d3eb: 'Equipment Category Grid' # Equipment Category Grid
    e2e75496-e9a6-4b2c-9f2f-3e9ea139a3b1: 'Hero with Breadcrumbs' # Hero with Breadcrumbs
    e6ecaa86-d570-4965-b85f-62c9ff23b0d7: 'Equipment Page Content' # Equipment Page Content
    e7076da7-39d5-4fe9-bca1-588f96d22b04: Label # Label
    efb6f34c-41f5-4d47-bda7-2f96b491d19c: 'Single Link' # Single Link
    efe6c18d-5435-400c-92da-48306d6a6da9: 'Equipment Page Type' # Equipment Page Type
    f0170a2a-3987-4b96-a0b8-e2f4c9b4f177: 'Equipment Card' # Equipment Card
    f5a66dd0-a9c7-408c-b28f-6409042afd08: Pages # Pages
    f455cfbd-b7d8-4140-a7d2-4121bb10fbbd: Images # Images
    f676a57e-2621-4ec0-809a-0ad087bb9878: 'Product Tag' # Product Tag
    f9651f2a-e0c5-420e-bcd0-60892652fbcd: 'Newsletter Signup Banner' # Newsletter Signup Banner
    fab0c052-2ecc-4fb3-b50c-072289e0957f: True/False # True/False
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  breadcrumb:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  freeform:
    edition: lite
    enabled: true
    licenseKey: 4G1UNMER53QINOPYWGLDLNZT
    schemaVersion: 5.6.1
    settings:
      emailTemplateMethod: global
  templatecomments:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Sub
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
