dateModified: 1751884873
email:
  fromEmail: dev@in-testing.co.uk
  fromName: Sub
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@uploads'
meta:
  __names__:
    0b0b67e9-a4bb-48cf-8316-808106205fec: 'Single Column Text Block' # Single Column Text Block
    0b7df609-3386-44d6-8dec-9236996e999a: 'Link List' # Link List
    0de456be-e57c-491d-b5e9-2a48c94a73cf: 'Fifty Fifty Card' # Fifty Fifty Card
    1b4f2218-99f7-4c9f-bef2-d0a2afb38294: 'Wanted Equipment List' # Wanted Equipment List
    01ce057f-6e39-430f-9d43-c40aa57cb04c: 'Image Carousel' # Image Carousel
    1ed4c77a-2163-41cd-a3b4-dac5650b0ea3: 'Equipment List Pages' # Equipment List Pages
    2ab2d3a7-a361-4842-9ce1-e8903cdc9b11: 'Page Card' # Page Card
    3a4016c0-b8ce-4030-a761-17bbd4cb565f: 'Listing Card Tag' # Listing Card Tag
    6e678c67-681a-4c23-bcb6-a67780aa5008: Table # Table
    8c5c2d88-d621-448b-81ae-1f21849e4f56: Sub # Sub
    9e240243-7493-415d-ab07-371200775874: 'Wanted Equipment Card' # Wanted Equipment Card
    25b44531-448b-4689-84e9-8af1f8ebda2a: 'Wanted Equipment Tags' # Wanted Equipment Tags
    27b88dbb-5275-488c-8cb3-86e8daa4b84f: 'Equipment Page Type' # Equipment Page Type
    37bcb295-e211-4822-b8ef-9119df20f58e: 'Page Content' # Page Content
    40e39d39-823a-4baa-9f2d-4c0062a61789: 'Category Listing Block' # Category Listing Block
    46e91064-492e-4832-8b32-9ea816047e2d: Heading # Heading
    67dc91f5-0d77-46ec-9598-895f0fcb0153: 'Table with Form Block' # Table with Form Block
    75c37449-5a52-49a5-9e4a-f3533695f300: Navigation # Navigation
    76a49bc6-7217-453a-a9d2-2d2c585b70a6: 'Page Cards' # Page Cards
    114e0eaa-67db-473a-a450-04a4a53bba35: Footer # Footer
    150f8082-44e6-4d6f-98b5-07294c51622e: 'Wanted Equipment Categories' # Wanted Equipment Categories
    208b59dc-efeb-404c-98f2-6ec660879ee1: 'Single Link' # Single Link
    596d6ee6-2460-4cb0-b5ca-5c9470c79049: 'Wanted Equipment Listing Block' # Wanted Equipment Listing Block
    674fb744-b160-444b-af35-72f3a327afbf: 'Two Column Card Block' # Two Column Card Block
    741d13d8-7c1b-4440-a507-1b6478eb6736: 'Fifty Fifty Repeater' # Fifty Fifty Repeater
    861d3103-01e5-446c-b19c-8357db15e40d: Header # Header
    09043f1e-ea69-4028-8ca3-5f75660d3d3d: Subtext # Subtext
    20033fea-bd0d-4a3e-ad47-9f84788a37db: 'CTA With Background' # CTA With Background
    69332d09-4481-4eaf-9f75-241fbd7f5211: 'Megamenu Content' # Megamenu Content
    75863d2f-136d-4a26-9a25-513b18592b4c: 'Equipment Single Pages' # Equipment Single Pages
    312021f4-e37c-4cd4-a5cc-948fec2a9862: 'Product Page Details' # Product Page Details
    409531c9-59ff-4658-9ca0-41d34bc7bc30: Homepage # Homepage
    0877517c-0da8-4981-a651-1cb64f76d2bf: 'Wanted Equipment' # Wanted Equipment
    4494340c-3b4f-4bb8-a887-fa3b6f110dc1: Sub # Sub
    26919202-5503-4b47-913f-a7b707940ad8: Headings # Headings
    31515169-58e5-4fdf-b1f0-0060aba7da2f: Subtext # Subtext
    62534679-40fc-45ab-9544-cbced2386fe8: Media # Media
    a92e5168-e1b1-4553-88ea-8b38892b8c65: 'Megamenu List' # Megamenu List
    b375a142-d6d8-4f54-b238-08c6e1dc7e07: 'Detail Text' # Detail Text
    bb77f789-9d4a-4f63-a6a1-dc3102e8e063: 'Contact Page Form Block' # Contact Page Form Block
    bcded55c-424c-4973-b666-df8c107909d2: 'Equipment Cards' # Equipment Cards
    c190d294-d2f4-4f8b-a3f9-bbc414f9e870: Simple # Simple
    ca7c778b-1c9d-4e2a-83a5-984c98a48619: 'Main Content' # Main Content
    cb061430-787b-48ea-8a9b-c7980d0134b9: 'Megamenu Item' # Megamenu Item
    cc564f9e-b397-4f24-b3e3-efc92f2ec8e6: 'Featured Equipment Carousel' # Featured Equipment Carousel
    cdb88818-0242-4279-92e9-21a22e0931cb: '50/50 Image Text Repeater' # 50/50 Image Text Repeater
    d4e7a80b-80bb-4ab2-a2f1-c58e7d49ed90: 'Product Listing Block' # Product Listing Block
    db374a72-4262-4dd5-831f-80cbee218809: 'Carousel Slide' # Carousel Slide
    e1d477b7-f94e-41e1-94f9-0a657534d3eb: 'Equipment Category Grid' # Equipment Category Grid
    e2e75496-e9a6-4b2c-9f2f-3e9ea139a3b1: 'Hero with Breadcrumbs' # Hero with Breadcrumbs
    e6ecaa86-d570-4965-b85f-62c9ff23b0d7: 'Equipment Page Content' # Equipment Page Content
    e7076da7-39d5-4fe9-bca1-588f96d22b04: Label # Label
    eac6a48a-439c-456f-b037-4f29d8ca838c: 'Single Hero Block' # Single Hero Block
    eb464430-cc3f-4bba-8db7-7ba6d63af07e: 'Text with CTA Cards' # Text with CTA Cards
    efb6f34c-41f5-4d47-bda7-2f96b491d19c: 'Single Link' # Single Link
    efe6c18d-5435-400c-92da-48306d6a6da9: 'Equipment Page Type' # Equipment Page Type
    f0170a2a-3987-4b96-a0b8-e2f4c9b4f177: 'Equipment Card' # Equipment Card
    f5a66dd0-a9c7-408c-b28f-6409042afd08: Pages # Pages
    f455cfbd-b7d8-4140-a7d2-4121bb10fbbd: Images # Images
    f676a57e-2621-4ec0-809a-0ad087bb9878: 'Product Tag' # Product Tag
    f9651f2a-e0c5-420e-bcd0-60892652fbcd: 'Newsletter Signup Banner' # Newsletter Signup Banner
    fab0c052-2ecc-4fb3-b50c-072289e0957f: True/False # True/False
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  breadcrumb:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  freeform:
    edition: lite
    enabled: true
    licenseKey: 4G1UNMER53QINOPYWGLDLNZT
    schemaVersion: 5.6.1
    settings:
      alertNotificationRecipients: null
      allowBuilderTemplateCreation: true
      allowDashesInFieldHandles: false
      allowFileTemplateEdit: true
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: 1
      clientDigestRecipients: null
      csrfRefresh: none
      defaultFromEmail: '{{ general.systemEmail }}'
      defaultFromName: '{{ general.systemName }}'
      defaultView: forms
      defaults:
        __assoc__:
          -
            - previewHtml
            - true
          -
            - twigInHtml
            - true
          -
            - twigIsolation
            - true
          -
            - richTextFieldToolbarConfiguration
            - 'blocks bold italic underline forecolor backcolor | align numlist bullist | link image table | removeformat code'
          -
            - includeSampleTemplates
            - true
          -
            - notifications
            -
              __assoc__:
                -
                  - admin
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                -
                  - conditional
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                -
                  - userSelect
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                -
                  - emailField
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
          -
            - settings
            -
              __assoc__:
                -
                  - general
                  -
                    __assoc__:
                      -
                        - formType
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - Solspace\Freeform\Form\Types\Regular
                      -
                        - submissionTitle
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '{{ dateCreated|date("Y-m-d H:i:s") }}'
                      -
                        - formattingTemplate
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - basic-light/index.twig
                -
                  - dataStorage
                  -
                    __assoc__:
                      -
                        - storeData
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '1'
                      -
                        - defaultStatus
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '2'
                      -
                        - collectIp
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '1'
                -
                  - processing
                  -
                    __assoc__:
                      -
                        - ajax
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '1'
                      -
                        - showIndicator
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '1'
                      -
                        - showText
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '1'
                      -
                        - processingText
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - Processing...
                -
                  - successAndErrors
                  -
                    __assoc__:
                      -
                        - successBehavior
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - redirect-return-url
                      -
                        - returnUrl
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                      -
                        - successTemplate
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                      -
                        - successMessage
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - 'Form has been submitted successfully!'
                      -
                        - errorMessage
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - 'Sorry, there was an error submitting the form. Please try again.'
                -
                  - limits
                  -
                    __assoc__:
                      -
                        - duplicateCheck
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - no_limit
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailNotificationToolbarConfiguration: 'blocks bold italic underline forecolor backcolor | align numlist bullist | link image table | removeformat code'
      emailTemplateDefault: database
      emailTemplateDirectory: null
      emailTemplateMethod: global
      emailTemplateStorageType: files_database
      exportHandlesAsNames: false
      exportLabels: false
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: basic-light/index.twig
      loggingLevel: error
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      purgeAssets: true
      queuePriority: null
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: files
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      sitesEnabled: false
      spamFolderEnabled: true
      spamProtectionBehavior: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: null
      updateSearchIndexes: true
      useQueueForEmailNotifications: false
      useQueueForIntegrations: false
  templatecomments:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Sub
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
