fieldLayouts:
  ea7b3ff2-5631-42c4-af3c-7efb5338fcc6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-04T09:44:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7076da7-39d5-4fe9-bca1-588f96d22b04 # Label
            handle: systemEmail
            includeInCards: false
            instructions: null
            label: 'System Email'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0ed19d1-c0a0-4435-999f-b0744865dfc9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-04T09:44:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7076da7-39d5-4fe9-bca1-588f96d22b04 # Label
            handle: systemName
            includeInCards: false
            instructions: null
            label: 'System Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c50c08f-dc06-472f-b4bf-4a18e8c87d2a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61b49420-559e-472a-b9ad-e25d92dcfeb7
        userCondition: null
handle: general
name: General
sortOrder: 4
