fieldLayouts:
  3a029fa7-a9a5-4f07-b549-380784463d67:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-02T09:38:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ec030511-3ca4-4860-bf00-5396c90d7afb # Image
            handle: logo
            includeInCards: false
            instructions: null
            label: Logo
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 331c6f9c-398d-49a4-849a-79bdd8cd5544
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-02T09:37:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7237097a-258e-4778-abe5-339d6c644bba # Navigation
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4d832cc-5f76-4d94-a6f4-608b24cb09eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-02T11:00:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5c1e6b6c-f11d-42c0-9506-3aeec1df72fd # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18f76b90-1947-4359-b864-05e47b676e59
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d99e8e8-66c0-4b6b-ba80-537c2bda22e9
        userCondition: null
handle: header
name: Header
sortOrder: 1
