defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3fb67b16-5a13-4db3-a0bd-b370a28dda1b # Pages
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8eb5e56d-5ba1-4f2e-a8e1-26feebd5553d: # Ideal Insights
    enabledByDefault: true
    hasUrls: true
    template: pages/_homepage.twig
    uriFormat: __home__
type: single
